# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.1.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Roz
has_binder: false
has_settings: false
kind: theme
labextension_name: roz-thm
project_short_description: A JupyterLab theme.
python_name: roz_thm
repository: ''
test: false

